export interface EnglishWord {
  id: string;
  en: string;
  cs: string;
  emoji: string;
  category: string;
}

export const ENGLISH_WORDS: EnglishWord[] = [
  // Zvířata
  { id: "cat", en: "cat", cs: "kočka", emoji: "🐱", category: "Zvířata" },
  { id: "dog", en: "dog", cs: "pes", emoji: "🐶", category: "Zvířata" },
  { id: "fish", en: "fish", cs: "ryba", emoji: "🐟", category: "Zvířata" },
  { id: "bird", en: "bird", cs: "pták", emoji: "🐦", category: "Zvířata" },
  { id: "horse", en: "horse", cs: "kůň", emoji: "🐴", category: "Zvířata" },
  { id: "cow", en: "cow", cs: "kráva", emoji: "🐄", category: "Zvířata" },
  { id: "pig", en: "pig", cs: "prase", emoji: "🐷", category: "Zvířata" },
  { id: "sheep", en: "sheep", cs: "ovce", emoji: "🐑", category: "Zvířata" },
  { id: "goat", en: "goat", cs: "koza", emoji: "🐐", category: "Zvířata" },
  { id: "chicken", en: "chicken", cs: "slepice", emoji: "🐔", category: "Zvířata" },
  { id: "duck", en: "duck", cs: "kachna", emoji: "🦆", category: "Zvířata" },
  { id: "goose", en: "goose", cs: "husa", emoji: "🪿", category: "Zvířata" },
  { id: "rabbit", en: "rabbit", cs: "králík", emoji: "🐰", category: "Zvířata" },
  { id: "mouse", en: "mouse", cs: "myš", emoji: "🐭", category: "Zvířata" },
  { id: "rat", en: "rat", cs: "krysa", emoji: "🐀", category: "Zvířata" },
  { id: "hamster", en: "hamster", cs: "křeček", emoji: "🐹", category: "Zvířata" },
  { id: "turtle", en: "turtle", cs: "želva", emoji: "🐢", category: "Zvířata" },
  { id: "snake", en: "snake", cs: "had", emoji: "🐍", category: "Zvířata" },
  { id: "lizard", en: "lizard", cs: "ještěrka", emoji: "🦎", category: "Zvířata" },
  { id: "frog", en: "frog", cs: "žába", emoji: "🐸", category: "Zvířata" },
  { id: "spider", en: "spider", cs: "pavouk", emoji: "🕷️", category: "Zvířata" },
  { id: "bee", en: "bee", cs: "včela", emoji: "🐝", category: "Zvířata" },
  { id: "ant", en: "ant", cs: "mravenec", emoji: "🐜", category: "Zvířata" },
  { id: "butterfly", en: "butterfly", cs: "motýl", emoji: "🦋", category: "Zvířata" },
  { id: "ladybug", en: "ladybug", cs: "beruška", emoji: "🐞", category: "Zvířata" },
  { id: "snail", en: "snail", cs: "hlemýžď", emoji: "🐌", category: "Zvířata" },
  { id: "worm", en: "worm", cs: "červ", emoji: "🪱", category: "Zvířata" },
  { id: "housefly", en: "housefly", cs: "moucha", emoji: "🪰", category: "Zvířata" },
  { id: "mosquito", en: "mosquito", cs: "komár", emoji: "🦟", category: "Zvířata" },
  { id: "lion", en: "lion", cs: "lev", emoji: "🦁", category: "Zvířata" },
  { id: "tiger", en: "tiger", cs: "tygr", emoji: "🐯", category: "Zvířata" },
  { id: "elephant", en: "elephant", cs: "slon", emoji: "🐘", category: "Zvířata" },
  { id: "giraffe", en: "giraffe", cs: "žirafa", emoji: "🦒", category: "Zvířata" },
  { id: "zebra", en: "zebra", cs: "zebra", emoji: "🦓", category: "Zvířata" },
  { id: "monkey", en: "monkey", cs: "opice", emoji: "🐵", category: "Zvířata" },
  { id: "gorilla", en: "gorilla", cs: "gorila", emoji: "🦍", category: "Zvířata" },
  { id: "bear", en: "bear", cs: "medvěd", emoji: "🐻", category: "Zvířata" },
  { id: "panda", en: "panda", cs: "panda", emoji: "🐼", category: "Zvířata" },
  { id: "koala", en: "koala", cs: "koala", emoji: "🐨", category: "Zvířata" },
  { id: "kangaroo", en: "kangaroo", cs: "klokan", emoji: "🦘", category: "Zvířata" },
  { id: "wolf", en: "wolf", cs: "vlk", emoji: "🐺", category: "Zvířata" },
  { id: "fox", en: "fox", cs: "liška", emoji: "🦊", category: "Zvířata" },
  { id: "deer", en: "deer", cs: "jelen", emoji: "🦌", category: "Zvířata" },
  { id: "squirrel", en: "squirrel", cs: "veverka", emoji: "🐿️", category: "Zvířata" },
  { id: "hedgehog", en: "hedgehog", cs: "ježek", emoji: "🦔", category: "Zvířata" },
  { id: "bat", en: "bat", cs: "netopýr", emoji: "🦇", category: "Zvířata" },
  { id: "owl", en: "owl", cs: "sova", emoji: "🦉", category: "Zvířata" },
  { id: "eagle", en: "eagle", cs: "orel", emoji: "🦅", category: "Zvířata" },
  { id: "parrot", en: "parrot", cs: "papoušek", emoji: "🦜", category: "Zvířata" },
  { id: "penguin", en: "penguin", cs: "tučňák", emoji: "🐧", category: "Zvířata" },
  { id: "peacock", en: "peacock", cs: "páv", emoji: "🦚", category: "Zvířata" },
  { id: "swan", en: "swan", cs: "labuť", emoji: "🦢", category: "Zvířata" },
  { id: "flamingo", en: "flamingo", cs: "plameňák", emoji: "🦩", category: "Zvířata" },
  { id: "crow", en: "crow", cs: "vrána", emoji: "🐦‍⬛", category: "Zvířata" },
  { id: "dove", en: "dove", cs: "holubice", emoji: "🕊️", category: "Zvířata" },
  { id: "turkey", en: "turkey", cs: "krocan", emoji: "🦃", category: "Zvířata" },
  { id: "camel", en: "camel", cs: "velbloud", emoji: "🐫", category: "Zvířata" },
  { id: "donkey", en: "donkey", cs: "osel", emoji: "🫏", category: "Zvířata" },
  { id: "hippo", en: "hippo", cs: "hroch", emoji: "🦛", category: "Zvířata" },
  { id: "rhino", en: "rhino", cs: "nosorožec", emoji: "🦏", category: "Zvířata" },
  { id: "crocodile", en: "crocodile", cs: "krokodýl", emoji: "🐊", category: "Zvířata" },
  { id: "shark", en: "shark", cs: "žralok", emoji: "🦈", category: "Zvířata" },
  { id: "whale", en: "whale", cs: "velryba", emoji: "🐳", category: "Zvířata" },
  { id: "dolphin", en: "dolphin", cs: "delfín", emoji: "🐬", category: "Zvířata" },
  { id: "octopus", en: "octopus", cs: "chobotnice", emoji: "🐙", category: "Zvířata" },
  { id: "crab", en: "crab", cs: "krab", emoji: "🦀", category: "Zvířata" },
  { id: "lobster", en: "lobster", cs: "humr", emoji: "🦞", category: "Zvířata" },
  { id: "shrimp", en: "shrimp", cs: "kreveta", emoji: "🦐", category: "Zvířata" },
  { id: "jellyfish", en: "jellyfish", cs: "medúza", emoji: "🪼", category: "Zvířata" },
  { id: "seal", en: "seal", cs: "tuleň", emoji: "🦭", category: "Zvířata" },
  { id: "otter", en: "otter", cs: "vydra", emoji: "🦦", category: "Zvířata" },
  { id: "raccoon", en: "raccoon", cs: "mýval", emoji: "🦝", category: "Zvířata" },
  { id: "skunk", en: "skunk", cs: "skunk", emoji: "🦨", category: "Zvířata" },
  { id: "moose", en: "moose", cs: "los", emoji: "🫎", category: "Zvířata" },
  { id: "buffalo", en: "buffalo", cs: "buvol", emoji: "🐃", category: "Zvířata" },
  { id: "leopard", en: "leopard", cs: "levhart", emoji: "🐆", category: "Zvířata" },
  { id: "sloth", en: "sloth", cs: "lenochod", emoji: "🦥", category: "Zvířata" },
  { id: "badger", en: "badger", cs: "jezevec", emoji: "🦡", category: "Zvířata" },
  { id: "hare", en: "hare", cs: "zajíc", emoji: "🐇", category: "Zvířata" },
  { id: "chick", en: "chick", cs: "kuře", emoji: "🐤", category: "Zvířata" },
  { id: "cricket", en: "cricket", cs: "cvrček", emoji: "🦗", category: "Zvířata" },
  { id: "scorpion", en: "scorpion", cs: "štír", emoji: "🦂", category: "Zvířata" },
  { id: "dinosaur", en: "dinosaur", cs: "dinosaurus", emoji: "🦕", category: "Zvířata" },
  { id: "unicorn", en: "unicorn", cs: "jednorožec", emoji: "🦄", category: "Zvířata" },

  // Jídlo
  { id: "apple", en: "apple", cs: "jablko", emoji: "🍎", category: "Jídlo" },
  { id: "banana", en: "banana", cs: "banán", emoji: "🍌", category: "Jídlo" },
  { id: "orange", en: "orange", cs: "pomeranč", emoji: "🍊", category: "Jídlo" },
  { id: "grape", en: "grape", cs: "hroznové víno", emoji: "🍇", category: "Jídlo" },
  { id: "strawberry", en: "strawberry", cs: "jahoda", emoji: "🍓", category: "Jídlo" },
  { id: "watermelon", en: "watermelon", cs: "meloun", emoji: "🍉", category: "Jídlo" },
  { id: "pineapple", en: "pineapple", cs: "ananas", emoji: "🍍", category: "Jídlo" },
  { id: "lemon", en: "lemon", cs: "citron", emoji: "🍋", category: "Jídlo" },
  { id: "cherry", en: "cherry", cs: "třešeň", emoji: "🍒", category: "Jídlo" },
  { id: "peach", en: "peach", cs: "broskev", emoji: "🍑", category: "Jídlo" },
  { id: "pear", en: "pear", cs: "hruška", emoji: "🍐", category: "Jídlo" },
  { id: "mango", en: "mango", cs: "mango", emoji: "🥭", category: "Jídlo" },
  { id: "kiwi", en: "kiwi", cs: "kiwi", emoji: "🥝", category: "Jídlo" },
  { id: "coconut", en: "coconut", cs: "kokos", emoji: "🥥", category: "Jídlo" },
  { id: "avocado", en: "avocado", cs: "avokádo", emoji: "🥑", category: "Jídlo" },
  { id: "carrot", en: "carrot", cs: "mrkev", emoji: "🥕", category: "Jídlo" },
  { id: "potato", en: "potato", cs: "brambora", emoji: "🥔", category: "Jídlo" },
  { id: "tomato", en: "tomato", cs: "rajče", emoji: "🍅", category: "Jídlo" },
  { id: "onion", en: "onion", cs: "cibule", emoji: "🧅", category: "Jídlo" },
  { id: "garlic", en: "garlic", cs: "česnek", emoji: "🧄", category: "Jídlo" },
  { id: "cucumber", en: "cucumber", cs: "okurka", emoji: "🥒", category: "Jídlo" },
  { id: "pepper", en: "pepper", cs: "paprika", emoji: "🫑", category: "Jídlo" },
  { id: "corn", en: "corn", cs: "kukuřice", emoji: "🌽", category: "Jídlo" },
  { id: "broccoli", en: "broccoli", cs: "brokolice", emoji: "🥦", category: "Jídlo" },
  { id: "cabbage", en: "cabbage", cs: "zelí", emoji: "🥬", category: "Jídlo" },
  { id: "mushroom", en: "mushroom", cs: "houba", emoji: "🍄", category: "Jídlo" },
  { id: "pumpkin", en: "pumpkin", cs: "dýně", emoji: "🎃", category: "Jídlo" },
  { id: "pea", en: "pea", cs: "hrášek", emoji: "🫛", category: "Jídlo" },
  { id: "eggplant", en: "eggplant", cs: "lilek", emoji: "🍆", category: "Jídlo" },
  { id: "bread", en: "bread", cs: "chléb", emoji: "🍞", category: "Jídlo" },
  { id: "cheese", en: "cheese", cs: "sýr", emoji: "🧀", category: "Jídlo" },
  { id: "butter", en: "butter", cs: "máslo", emoji: "🧈", category: "Jídlo" },
  { id: "milk", en: "milk", cs: "mléko", emoji: "🥛", category: "Jídlo" },
  { id: "egg", en: "egg", cs: "vejce", emoji: "🥚", category: "Jídlo" },
  { id: "bacon", en: "bacon", cs: "slanina", emoji: "🥓", category: "Jídlo" },
  { id: "salt", en: "salt", cs: "sůl", emoji: "🧂", category: "Jídlo" },
  { id: "rice", en: "rice", cs: "rýže", emoji: "🍚", category: "Jídlo" },
  { id: "pasta", en: "pasta", cs: "těstoviny", emoji: "🍝", category: "Jídlo" },
  { id: "soup", en: "soup", cs: "polévka", emoji: "🍲", category: "Jídlo" },
  { id: "sandwich", en: "sandwich", cs: "sendvič", emoji: "🥪", category: "Jídlo" },
  { id: "pizza", en: "pizza", cs: "pizza", emoji: "🍕", category: "Jídlo" },
  { id: "hamburger", en: "hamburger", cs: "hamburger", emoji: "🍔", category: "Jídlo" },
  { id: "hotdog", en: "hotdog", cs: "párek v rohlíku", emoji: "🌭", category: "Jídlo" },
  { id: "fries", en: "fries", cs: "hranolky", emoji: "🍟", category: "Jídlo" },
  { id: "popcorn", en: "popcorn", cs: "popcorn", emoji: "🍿", category: "Jídlo" },
  { id: "pancake", en: "pancake", cs: "palačinka", emoji: "🥞", category: "Jídlo" },
  { id: "waffle", en: "waffle", cs: "vafle", emoji: "🧇", category: "Jídlo" },
  { id: "donut", en: "donut", cs: "donut", emoji: "🍩", category: "Jídlo" },
  { id: "cake", en: "cake", cs: "dort", emoji: "🍰", category: "Jídlo" },
  { id: "cookie", en: "cookie", cs: "sušenka", emoji: "🍪", category: "Jídlo" },
  { id: "chocolate", en: "chocolate", cs: "čokoláda", emoji: "🍫", category: "Jídlo" },
  { id: "candy", en: "candy", cs: "bonbón", emoji: "🍬", category: "Jídlo" },
  { id: "ice_cream", en: "ice cream", cs: "zmrzlina", emoji: "🍦", category: "Jídlo" },
  { id: "cereal", en: "cereal", cs: "cereálie", emoji: "🥣", category: "Jídlo" },
  { id: "steak", en: "steak", cs: "steak", emoji: "🥩", category: "Jídlo" },
  { id: "juice", en: "juice", cs: "džus", emoji: "🧃", category: "Jídlo" },
  { id: "water", en: "water", cs: "voda", emoji: "💧", category: "Jídlo" },
  { id: "tea", en: "tea", cs: "čaj", emoji: "🍵", category: "Jídlo" },
  { id: "coffee", en: "coffee", cs: "káva", emoji: "☕", category: "Jídlo" },
  { id: "pie", en: "pie", cs: "koláč", emoji: "🥧", category: "Jídlo" },
  { id: "pretzel", en: "pretzel", cs: "preclík", emoji: "🥨", category: "Jídlo" },
  { id: "peanut", en: "peanut", cs: "burák", emoji: "🥜", category: "Jídlo" },
  { id: "chestnut", en: "chestnut", cs: "kaštan", emoji: "🌰", category: "Jídlo" },
  { id: "olive", en: "olive", cs: "oliva", emoji: "🫒", category: "Jídlo" },
  { id: "noodles", en: "noodles", cs: "nudle", emoji: "🍜", category: "Jídlo" },
  { id: "taco", en: "taco", cs: "taco", emoji: "🌮", category: "Jídlo" },
  { id: "burrito", en: "burrito", cs: "burrito", emoji: "🌯", category: "Jídlo" },
  { id: "sushi", en: "sushi", cs: "sushi", emoji: "🍣", category: "Jídlo" },
  { id: "dumpling", en: "dumpling", cs: "knedlík", emoji: "🥟", category: "Jídlo" },
  { id: "croissant", en: "croissant", cs: "croissant", emoji: "🥐", category: "Jídlo" },
  { id: "bagel", en: "bagel", cs: "bagel", emoji: "🥯", category: "Jídlo" },
  { id: "lollipop", en: "lollipop", cs: "lízátko", emoji: "🍭", category: "Jídlo" },
  { id: "cupcake", en: "cupcake", cs: "košíček", emoji: "🧁", category: "Jídlo" },
  { id: "honey", en: "honey", cs: "med", emoji: "🍯", category: "Jídlo" },

  // Doma
  { id: "house", en: "house", cs: "dům", emoji: "🏠", category: "Doma" },
  { id: "door", en: "door", cs: "dveře", emoji: "🚪", category: "Doma" },
  { id: "window", en: "window", cs: "okno", emoji: "🪟", category: "Doma" },
  { id: "chair", en: "chair", cs: "židle", emoji: "🪑", category: "Doma" },
  { id: "bed", en: "bed", cs: "postel", emoji: "🛏️", category: "Doma" },
  { id: "sofa", en: "sofa", cs: "pohovka", emoji: "🛋️", category: "Doma" },
  { id: "lamp", en: "lamp", cs: "lampa", emoji: "💡", category: "Doma" },
  { id: "clock", en: "clock", cs: "hodiny", emoji: "🕐", category: "Doma" },
  { id: "mirror", en: "mirror", cs: "zrcadlo", emoji: "🪞", category: "Doma" },
  { id: "key", en: "key", cs: "klíč", emoji: "🔑", category: "Doma" },
  { id: "book", en: "book", cs: "kniha", emoji: "📖", category: "Doma" },
  { id: "pen", en: "pen", cs: "pero", emoji: "🖊️", category: "Doma" },
  { id: "pencil", en: "pencil", cs: "tužka", emoji: "✏️", category: "Doma" },
  { id: "phone", en: "phone", cs: "telefon", emoji: "📱", category: "Doma" },
  { id: "computer", en: "computer", cs: "počítač", emoji: "💻", category: "Doma" },
  { id: "television", en: "television", cs: "televize", emoji: "📺", category: "Doma" },
  { id: "radio", en: "radio", cs: "rádio", emoji: "📻", category: "Doma" },
  { id: "camera", en: "camera", cs: "fotoaparát", emoji: "📷", category: "Doma" },
  { id: "umbrella", en: "umbrella", cs: "deštník", emoji: "☂️", category: "Doma" },
  { id: "backpack", en: "backpack", cs: "batoh", emoji: "🎒", category: "Doma" },
  { id: "box", en: "box", cs: "krabice", emoji: "📦", category: "Doma" },
  { id: "bottle", en: "bottle", cs: "láhev", emoji: "🧴", category: "Doma" },
  { id: "plate", en: "plate", cs: "talíř", emoji: "🍽️", category: "Doma" },
  { id: "spoon", en: "spoon", cs: "lžíce", emoji: "🥄", category: "Doma" },
  { id: "fork", en: "fork", cs: "vidlička", emoji: "🍴", category: "Doma" },
  { id: "knife", en: "knife", cs: "nůž", emoji: "🔪", category: "Doma" },
  { id: "pan", en: "pan", cs: "pánev", emoji: "🍳", category: "Doma" },
  { id: "soap", en: "soap", cs: "mýdlo", emoji: "🧼", category: "Doma" },
  { id: "toothbrush", en: "toothbrush", cs: "kartáček na zuby", emoji: "🪥", category: "Doma" },
  { id: "brush", en: "brush", cs: "kartáč na vlasy", emoji: "🪮", category: "Doma" },
  { id: "broom", en: "broom", cs: "koště", emoji: "🧹", category: "Doma" },
  { id: "bucket", en: "bucket", cs: "kbelík", emoji: "🪣", category: "Doma" },
  { id: "ladder", en: "ladder", cs: "žebřík", emoji: "🪜", category: "Doma" },
  { id: "hammer", en: "hammer", cs: "kladivo", emoji: "🔨", category: "Doma" },
  { id: "scissors", en: "scissors", cs: "nůžky", emoji: "✂️", category: "Doma" },
  { id: "thread", en: "thread", cs: "nit", emoji: "🧵", category: "Doma" },
  { id: "candle", en: "candle", cs: "svíčka", emoji: "🕯️", category: "Doma" },
  { id: "battery", en: "battery", cs: "baterie", emoji: "🔋", category: "Doma" },
  { id: "coin", en: "coin", cs: "mince", emoji: "💰", category: "Doma" },
  { id: "glasses", en: "glasses", cs: "brýle", emoji: "👓", category: "Doma" },
  { id: "watch", en: "watch", cs: "hodinky", emoji: "⌚", category: "Doma" },
  { id: "ring", en: "ring", cs: "prsten", emoji: "💍", category: "Doma" },
  { id: "gift", en: "gift", cs: "dárek", emoji: "🎁", category: "Doma" },
  { id: "balloon", en: "balloon", cs: "balónek", emoji: "🎈", category: "Doma" },
  { id: "kite", en: "kite", cs: "papírový drak", emoji: "🪁", category: "Doma" },
  { id: "teddy_bear", en: "teddy bear", cs: "plyšový medvídek", emoji: "🧸", category: "Doma" },
  { id: "puzzle", en: "puzzle", cs: "skládačka", emoji: "🧩", category: "Doma" },
  { id: "block", en: "block", cs: "stavební kostka", emoji: "🧱", category: "Doma" },
  { id: "bell", en: "bell", cs: "zvonek", emoji: "🔔", category: "Doma" },
  { id: "flag", en: "flag", cs: "vlajka", emoji: "🚩", category: "Doma" },
  { id: "suitcase", en: "suitcase", cs: "kufr", emoji: "🧳", category: "Doma" },
  { id: "newspaper", en: "newspaper", cs: "noviny", emoji: "📰", category: "Doma" },
  { id: "letter", en: "letter", cs: "dopis", emoji: "✉️", category: "Doma" },
  { id: "map", en: "map", cs: "mapa", emoji: "🗺️", category: "Doma" },
  { id: "flashlight", en: "flashlight", cs: "baterka", emoji: "🔦", category: "Doma" },
  { id: "rope", en: "rope", cs: "lano", emoji: "🪢", category: "Doma" },
  { id: "paint", en: "paint", cs: "barva na malování", emoji: "🎨", category: "Doma" },
  { id: "trash_can", en: "trash can", cs: "popelnice", emoji: "🗑️", category: "Doma" },
  { id: "toilet", en: "toilet", cs: "záchod", emoji: "🚽", category: "Doma" },
  { id: "bathtub", en: "bathtub", cs: "vana", emoji: "🛁", category: "Doma" },
  { id: "shower", en: "shower", cs: "sprcha", emoji: "🚿", category: "Doma" },

  // Tělo
  { id: "face", en: "face", cs: "obličej", emoji: "🙂", category: "Tělo" },
  { id: "eye", en: "eye", cs: "oko", emoji: "👁️", category: "Tělo" },
  { id: "ear", en: "ear", cs: "ucho", emoji: "👂", category: "Tělo" },
  { id: "nose", en: "nose", cs: "nos", emoji: "👃", category: "Tělo" },
  { id: "mouth", en: "mouth", cs: "ústa", emoji: "👄", category: "Tělo" },
  { id: "tooth", en: "tooth", cs: "zub", emoji: "🦷", category: "Tělo" },
  { id: "tongue", en: "tongue", cs: "jazyk", emoji: "👅", category: "Tělo" },
  { id: "hair", en: "hair", cs: "vlasy", emoji: "🦱", category: "Tělo" },
  { id: "arm", en: "arm", cs: "paže", emoji: "💪", category: "Tělo" },
  { id: "hand", en: "hand", cs: "ruka", emoji: "✋", category: "Tělo" },
  { id: "finger", en: "finger", cs: "prst", emoji: "👆", category: "Tělo" },
  { id: "thumb", en: "thumb", cs: "palec", emoji: "👍", category: "Tělo" },
  { id: "leg", en: "leg", cs: "noha", emoji: "🦵", category: "Tělo" },
  { id: "foot", en: "foot", cs: "chodidlo", emoji: "🦶", category: "Tělo" },
  { id: "heart", en: "heart", cs: "srdce", emoji: "❤️", category: "Tělo" },
  { id: "brain", en: "brain", cs: "mozek", emoji: "🧠", category: "Tělo" },
  { id: "nail", en: "nail", cs: "nehet", emoji: "💅", category: "Tělo" },
  { id: "bone", en: "bone", cs: "kost", emoji: "🦴", category: "Tělo" },
  { id: "blood", en: "blood", cs: "krev", emoji: "🩸", category: "Tělo" },
  { id: "skeleton", en: "skeleton", cs: "kostra", emoji: "💀", category: "Tělo" },
  { id: "fist", en: "fist", cs: "pěst", emoji: "✊", category: "Tělo" },

  // Oblečení
  { id: "tshirt", en: "t-shirt", cs: "tričko", emoji: "👕", category: "Oblečení" },
  { id: "pants", en: "pants", cs: "kalhoty", emoji: "👖", category: "Oblečení" },
  { id: "shorts", en: "shorts", cs: "kraťasy", emoji: "🩳", category: "Oblečení" },
  { id: "dress", en: "dress", cs: "šaty", emoji: "👗", category: "Oblečení" },
  { id: "jacket", en: "jacket", cs: "bunda", emoji: "🧥", category: "Oblečení" },
  { id: "socks", en: "socks", cs: "ponožky", emoji: "🧦", category: "Oblečení" },
  { id: "shoes", en: "shoes", cs: "boty", emoji: "👞", category: "Oblečení" },
  { id: "sneakers", en: "sneakers", cs: "tenisky", emoji: "👟", category: "Oblečení" },
  { id: "boots", en: "boots", cs: "kozačky", emoji: "👢", category: "Oblečení" },
  { id: "hat", en: "hat", cs: "klobouk", emoji: "🎩", category: "Oblečení" },
  { id: "cap", en: "cap", cs: "kšiltovka", emoji: "🧢", category: "Oblečení" },
  { id: "scarf", en: "scarf", cs: "šála", emoji: "🧣", category: "Oblečení" },
  { id: "gloves", en: "gloves", cs: "rukavice", emoji: "🧤", category: "Oblečení" },
  { id: "tie", en: "tie", cs: "kravata", emoji: "👔", category: "Oblečení" },
  { id: "swimsuit", en: "swimsuit", cs: "plavky", emoji: "🩱", category: "Oblečení" },
  { id: "crown", en: "crown", cs: "koruna", emoji: "👑", category: "Oblečení" },
  { id: "sunglasses", en: "sunglasses", cs: "sluneční brýle", emoji: "🕶️", category: "Oblečení" },
  { id: "purse", en: "purse", cs: "kabelka", emoji: "👛", category: "Oblečení" },
  { id: "helmet", en: "helmet", cs: "helma", emoji: "⛑️", category: "Oblečení" },

  // Škola
  { id: "school", en: "school", cs: "škola", emoji: "🏫", category: "Škola" },
  { id: "teacher", en: "teacher", cs: "učitel", emoji: "🧑‍🏫", category: "Škola" },
  { id: "student", en: "student", cs: "student", emoji: "🧑‍🎓", category: "Škola" },
  { id: "ruler", en: "ruler", cs: "pravítko", emoji: "📏", category: "Škola" },
  { id: "notebook", en: "notebook", cs: "sešit", emoji: "📓", category: "Škola" },
  { id: "crayon", en: "crayon", cs: "pastelka", emoji: "🖍️", category: "Škola" },
  { id: "calculator", en: "calculator", cs: "kalkulačka", emoji: "🧮", category: "Škola" },
  { id: "globe", en: "globe", cs: "globus", emoji: "🌍", category: "Škola" },
  { id: "paintbrush", en: "paintbrush", cs: "štětec", emoji: "🖌️", category: "Škola" },
  { id: "diploma", en: "diploma", cs: "diplom", emoji: "📜", category: "Škola" },
  { id: "graduation_cap", en: "graduation cap", cs: "promoční čepice", emoji: "🎓", category: "Škola" },
  { id: "microscope", en: "microscope", cs: "mikroskop", emoji: "🔬", category: "Škola" },
  { id: "telescope", en: "telescope", cs: "dalekohled", emoji: "🔭", category: "Škola" },
  { id: "magnifying_glass", en: "magnifying glass", cs: "lupa", emoji: "🔍", category: "Škola" },
  { id: "homework", en: "homework", cs: "domácí úkol", emoji: "📝", category: "Škola" },
  { id: "library", en: "library", cs: "knihovna", emoji: "📚", category: "Škola" },
  { id: "dictionary", en: "dictionary", cs: "slovník", emoji: "📕", category: "Škola" },
  { id: "clipboard", en: "clipboard", cs: "deska s klipem", emoji: "📋", category: "Škola" },
  { id: "alphabet", en: "alphabet", cs: "abeceda", emoji: "🔤", category: "Škola" },
  { id: "paper", en: "paper", cs: "papír", emoji: "📄", category: "Škola" },
  { id: "folder", en: "folder", cs: "složka", emoji: "📁", category: "Škola" },

  // Příroda a počasí
  { id: "sun", en: "sun", cs: "slunce", emoji: "☀️", category: "Příroda a počasí" },
  { id: "moon", en: "moon", cs: "měsíc", emoji: "🌙", category: "Příroda a počasí" },
  { id: "star", en: "star", cs: "hvězda", emoji: "⭐", category: "Příroda a počasí" },
  { id: "cloud", en: "cloud", cs: "mrak", emoji: "☁️", category: "Příroda a počasí" },
  { id: "rain", en: "rain", cs: "déšť", emoji: "🌧️", category: "Příroda a počasí" },
  { id: "snow", en: "snow", cs: "sníh", emoji: "❄️", category: "Příroda a počasí" },
  { id: "wind", en: "wind", cs: "vítr", emoji: "💨", category: "Příroda a počasí" },
  { id: "storm", en: "storm", cs: "bouřka", emoji: "⛈️", category: "Příroda a počasí" },
  { id: "lightning", en: "lightning", cs: "blesk", emoji: "⚡", category: "Příroda a počasí" },
  { id: "rainbow", en: "rainbow", cs: "duha", emoji: "🌈", category: "Příroda a počasí" },
  { id: "tree", en: "tree", cs: "strom", emoji: "🌳", category: "Příroda a počasí" },
  { id: "flower", en: "flower", cs: "květina", emoji: "🌸", category: "Příroda a počasí" },
  { id: "grass", en: "grass", cs: "tráva", emoji: "🌱", category: "Příroda a počasí" },
  { id: "leaf", en: "leaf", cs: "list", emoji: "🍃", category: "Příroda a počasí" },
  { id: "mountain", en: "mountain", cs: "hora", emoji: "⛰️", category: "Příroda a počasí" },
  { id: "river", en: "river", cs: "řeka", emoji: "🏞️", category: "Příroda a počasí" },
  { id: "ocean", en: "ocean", cs: "moře", emoji: "🌊", category: "Příroda a počasí" },
  { id: "beach", en: "beach", cs: "pláž", emoji: "🏖️", category: "Příroda a počasí" },
  { id: "rock", en: "rock", cs: "kámen", emoji: "🪨", category: "Příroda a počasí" },
  { id: "volcano", en: "volcano", cs: "sopka", emoji: "🌋", category: "Příroda a počasí" },
  { id: "island", en: "island", cs: "ostrov", emoji: "🏝️", category: "Příroda a počasí" },
  { id: "forest", en: "forest", cs: "les", emoji: "🌲", category: "Příroda a počasí" },
  { id: "desert", en: "desert", cs: "poušť", emoji: "🏜️", category: "Příroda a počasí" },
  { id: "fire", en: "fire", cs: "oheň", emoji: "🔥", category: "Příroda a počasí" },
  { id: "ice", en: "ice", cs: "led", emoji: "🧊", category: "Příroda a počasí" },
  { id: "snowman", en: "snowman", cs: "sněhulák", emoji: "⛄", category: "Příroda a počasí" },
  { id: "fog", en: "fog", cs: "mlha", emoji: "🌫️", category: "Příroda a počasí" },
  { id: "tornado", en: "tornado", cs: "tornádo", emoji: "🌪️", category: "Příroda a počasí" },
  { id: "earth", en: "earth", cs: "Země", emoji: "🌍", category: "Příroda a počasí" },
  { id: "planet", en: "planet", cs: "planeta", emoji: "🪐", category: "Příroda a počasí" },

  // Doprava
  { id: "car", en: "car", cs: "auto", emoji: "🚗", category: "Doprava" },
  { id: "bus", en: "bus", cs: "autobus", emoji: "🚌", category: "Doprava" },
  { id: "train", en: "train", cs: "vlak", emoji: "🚆", category: "Doprava" },
  { id: "bicycle", en: "bicycle", cs: "kolo", emoji: "🚲", category: "Doprava" },
  { id: "motorcycle", en: "motorcycle", cs: "motorka", emoji: "🏍️", category: "Doprava" },
  { id: "airplane", en: "airplane", cs: "letadlo", emoji: "✈️", category: "Doprava" },
  { id: "helicopter", en: "helicopter", cs: "vrtulník", emoji: "🚁", category: "Doprava" },
  { id: "boat", en: "boat", cs: "loďka", emoji: "🚤", category: "Doprava" },
  { id: "ship", en: "ship", cs: "loď", emoji: "🚢", category: "Doprava" },
  { id: "truck", en: "truck", cs: "náklaďák", emoji: "🚚", category: "Doprava" },
  { id: "taxi", en: "taxi", cs: "taxi", emoji: "🚕", category: "Doprava" },
  { id: "ambulance", en: "ambulance", cs: "sanitka", emoji: "🚑", category: "Doprava" },
  { id: "firetruck", en: "firetruck", cs: "hasičské auto", emoji: "🚒", category: "Doprava" },
  { id: "police_car", en: "police car", cs: "policejní auto", emoji: "🚓", category: "Doprava" },
  { id: "tractor", en: "tractor", cs: "traktor", emoji: "🚜", category: "Doprava" },
  { id: "scooter", en: "scooter", cs: "koloběžka", emoji: "🛴", category: "Doprava" },
  { id: "skateboard", en: "skateboard", cs: "skateboard", emoji: "🛹", category: "Doprava" },
  { id: "rocket", en: "rocket", cs: "raketa", emoji: "🚀", category: "Doprava" },
  { id: "canoe", en: "canoe", cs: "kánoe", emoji: "🛶", category: "Doprava" },
  { id: "sailboat", en: "sailboat", cs: "plachetnice", emoji: "⛵", category: "Doprava" },
  { id: "tram", en: "tram", cs: "tramvaj", emoji: "🚊", category: "Doprava" },
  { id: "subway", en: "subway", cs: "metro", emoji: "🚇", category: "Doprava" },

  // Sport a koníčky
  { id: "soccer_ball", en: "soccer ball", cs: "fotbalový míč", emoji: "⚽", category: "Sport a koníčky" },
  { id: "basketball", en: "basketball", cs: "basketbal", emoji: "🏀", category: "Sport a koníčky" },
  { id: "football_american", en: "football", cs: "americký fotbal", emoji: "🏈", category: "Sport a koníčky" },
  { id: "baseball", en: "baseball", cs: "baseball", emoji: "⚾", category: "Sport a koníčky" },
  { id: "tennis", en: "tennis", cs: "tenis", emoji: "🎾", category: "Sport a koníčky" },
  { id: "volleyball", en: "volleyball", cs: "volejbal", emoji: "🏐", category: "Sport a koníčky" },
  { id: "golf", en: "golf", cs: "golf", emoji: "⛳", category: "Sport a koníčky" },
  { id: "swimming", en: "swimming", cs: "plavání", emoji: "🏊", category: "Sport a koníčky" },
  { id: "running", en: "running", cs: "běhání", emoji: "🏃", category: "Sport a koníčky" },
  { id: "cycling", en: "cycling", cs: "cyklistika", emoji: "🚴", category: "Sport a koníčky" },
  { id: "skiing", en: "skiing", cs: "lyžování", emoji: "⛷️", category: "Sport a koníčky" },
  { id: "skating", en: "skating", cs: "bruslení", emoji: "⛸️", category: "Sport a koníčky" },
  { id: "boxing", en: "boxing", cs: "box", emoji: "🥊", category: "Sport a koníčky" },
  { id: "yoga", en: "yoga", cs: "jóga", emoji: "🧘", category: "Sport a koníčky" },
  { id: "chess", en: "chess", cs: "šachy", emoji: "♟️", category: "Sport a koníčky" },
  { id: "cards", en: "cards", cs: "karty", emoji: "🃏", category: "Sport a koníčky" },
  { id: "guitar", en: "guitar", cs: "kytara", emoji: "🎸", category: "Sport a koníčky" },
  { id: "piano", en: "piano", cs: "piano", emoji: "🎹", category: "Sport a koníčky" },
  { id: "drum", en: "drum", cs: "buben", emoji: "🥁", category: "Sport a koníčky" },
  { id: "fishing", en: "fishing", cs: "rybaření", emoji: "🎣", category: "Sport a koníčky" },
  { id: "hiking", en: "hiking", cs: "turistika", emoji: "🥾", category: "Sport a koníčky" },
  { id: "bowling", en: "bowling", cs: "bowling", emoji: "🎳", category: "Sport a koníčky" },
  { id: "archery", en: "archery", cs: "lukostřelba", emoji: "🏹", category: "Sport a koníčky" },
  { id: "surfing", en: "surfing", cs: "surfování", emoji: "🏄", category: "Sport a koníčky" },
  { id: "trophy", en: "trophy", cs: "trofej", emoji: "🏆", category: "Sport a koníčky" },
  { id: "medal", en: "medal", cs: "medaile", emoji: "🏅", category: "Sport a koníčky" },
  { id: "badminton", en: "badminton", cs: "badminton", emoji: "🏸", category: "Sport a koníčky" },
  { id: "table_tennis", en: "table tennis", cs: "stolní tenis", emoji: "🏓", category: "Sport a koníčky" },
  { id: "weightlifting", en: "weightlifting", cs: "vzpírání", emoji: "🏋️", category: "Sport a koníčky" },
  { id: "sled", en: "sled", cs: "sáně", emoji: "🛷", category: "Sport a koníčky" },

  // Povolání
  { id: "doctor", en: "doctor", cs: "doktor", emoji: "🧑‍⚕️", category: "Povolání" },
  { id: "firefighter", en: "firefighter", cs: "hasič", emoji: "🧑‍🚒", category: "Povolání" },
  { id: "police_officer", en: "police officer", cs: "policista", emoji: "👮", category: "Povolání" },
  { id: "farmer", en: "farmer", cs: "farmář", emoji: "🧑‍🌾", category: "Povolání" },
  { id: "chef", en: "chef", cs: "kuchař", emoji: "🧑‍🍳", category: "Povolání" },
  { id: "pilot", en: "pilot", cs: "pilot", emoji: "🧑‍✈️", category: "Povolání" },
  { id: "astronaut", en: "astronaut", cs: "astronaut", emoji: "🧑‍🚀", category: "Povolání" },
  { id: "scientist", en: "scientist", cs: "vědec", emoji: "🧑‍🔬", category: "Povolání" },
  { id: "artist", en: "artist", cs: "umělec", emoji: "🧑‍🎨", category: "Povolání" },
  { id: "singer", en: "singer", cs: "zpěvák", emoji: "🎤", category: "Povolání" },
  { id: "mechanic", en: "mechanic", cs: "mechanik", emoji: "🧑‍🔧", category: "Povolání" },
  { id: "judge", en: "judge", cs: "soudce", emoji: "🧑‍⚖️", category: "Povolání" },
  { id: "prince", en: "prince", cs: "princ", emoji: "🤴", category: "Povolání" },
  { id: "princess", en: "princess", cs: "princezna", emoji: "👸", category: "Povolání" },
  { id: "wizard", en: "wizard", cs: "čaroděj", emoji: "🧙", category: "Povolání" },
  { id: "superhero", en: "superhero", cs: "superhrdina", emoji: "🦸", category: "Povolání" },
  { id: "clown", en: "clown", cs: "klaun", emoji: "🤡", category: "Povolání" },
  { id: "builder", en: "builder", cs: "stavební dělník", emoji: "👷", category: "Povolání" },
  { id: "photographer", en: "photographer", cs: "fotograf", emoji: "📸", category: "Povolání" },
  { id: "writer", en: "writer", cs: "spisovatel", emoji: "✍️", category: "Povolání" },

  // Slovesa
  { id: "run", en: "run", cs: "běžet", emoji: "🏃", category: "Slovesa" },
  { id: "jump", en: "jump", cs: "skákat", emoji: "🤸", category: "Slovesa" },
  { id: "walk", en: "walk", cs: "chodit", emoji: "🚶", category: "Slovesa" },
  { id: "eat", en: "eat", cs: "jíst", emoji: "🍽️", category: "Slovesa" },
  { id: "drink", en: "drink", cs: "pít", emoji: "🥤", category: "Slovesa" },
  { id: "sleep", en: "sleep", cs: "spát", emoji: "😴", category: "Slovesa" },
  { id: "swim", en: "swim", cs: "plavat", emoji: "🏊", category: "Slovesa" },
  { id: "fly", en: "fly", cs: "létat", emoji: "🛫", category: "Slovesa" },
  { id: "cry", en: "cry", cs: "plakat", emoji: "😢", category: "Slovesa" },
  { id: "laugh", en: "laugh", cs: "smát se", emoji: "😂", category: "Slovesa" },
  { id: "read", en: "read", cs: "číst", emoji: "📖", category: "Slovesa" },
  { id: "write", en: "write", cs: "psát", emoji: "✍️", category: "Slovesa" },
  { id: "cook", en: "cook", cs: "vařit", emoji: "🍳", category: "Slovesa" },
  { id: "drive", en: "drive", cs: "řídit", emoji: "🚗", category: "Slovesa" },
  { id: "sing", en: "sing", cs: "zpívat", emoji: "🎤", category: "Slovesa" },
  { id: "dance", en: "dance", cs: "tančit", emoji: "💃", category: "Slovesa" },
  { id: "climb", en: "climb", cs: "šplhat", emoji: "🧗", category: "Slovesa" },
  { id: "sit", en: "sit", cs: "sedět", emoji: "🪑", category: "Slovesa" },
  { id: "stand", en: "stand", cs: "stát", emoji: "🧍", category: "Slovesa" },
  { id: "wave", en: "wave", cs: "mávat", emoji: "👋", category: "Slovesa" },
  { id: "clap", en: "clap", cs: "tleskat", emoji: "👏", category: "Slovesa" },
  { id: "kick", en: "kick", cs: "kopat míč", emoji: "🦶", category: "Slovesa" },
  { id: "throw", en: "throw", cs: "házet", emoji: "🤾", category: "Slovesa" },
  { id: "open", en: "open", cs: "otevřít", emoji: "📂", category: "Slovesa" },
  { id: "close", en: "close", cs: "zavřít", emoji: "📁", category: "Slovesa" },
  { id: "wash", en: "wash", cs: "mýt", emoji: "🧼", category: "Slovesa" },
  { id: "draw", en: "draw", cs: "kreslit", emoji: "✏️", category: "Slovesa" },
  { id: "cut", en: "cut", cs: "stříhat", emoji: "✂️", category: "Slovesa" },
  { id: "build", en: "build", cs: "stavět", emoji: "🧱", category: "Slovesa" },
  { id: "clean_up", en: "clean up", cs: "uklízet", emoji: "🧹", category: "Slovesa" },
  { id: "ride", en: "ride", cs: "jet na kole", emoji: "🚴", category: "Slovesa" },
  { id: "hug", en: "hug", cs: "obejmout", emoji: "🤗", category: "Slovesa" },
  { id: "kiss", en: "kiss", cs: "políbit", emoji: "😘", category: "Slovesa" },
  { id: "smile", en: "smile", cs: "usmívat se", emoji: "😊", category: "Slovesa" },
  { id: "point", en: "point", cs: "ukazovat", emoji: "👉", category: "Slovesa" },
  { id: "listen", en: "listen", cs: "poslouchat", emoji: "👂", category: "Slovesa" },
  { id: "look", en: "look", cs: "dívat se", emoji: "👀", category: "Slovesa" },
  { id: "talk", en: "talk", cs: "mluvit", emoji: "🗣️", category: "Slovesa" },
  { id: "shout", en: "shout", cs: "křičet", emoji: "📢", category: "Slovesa" },
  { id: "plant", en: "plant", cs: "sázet", emoji: "🌱", category: "Slovesa" },
  { id: "hold", en: "hold", cs: "držet", emoji: "🤲", category: "Slovesa" },
  { id: "smell", en: "smell", cs: "čichat", emoji: "👃", category: "Slovesa" },
  { id: "touch", en: "touch", cs: "dotýkat se", emoji: "✋", category: "Slovesa" },
  { id: "wake_up", en: "wake up", cs: "probudit se", emoji: "⏰", category: "Slovesa" },
  { id: "count", en: "count", cs: "počítat", emoji: "🔢", category: "Slovesa" },
  { id: "pay", en: "pay", cs: "platit", emoji: "💳", category: "Slovesa" },
  { id: "shop", en: "shop", cs: "nakupovat", emoji: "🛒", category: "Slovesa" },
  { id: "camp", en: "camp", cs: "stanovat", emoji: "⛺", category: "Slovesa" },
  { id: "sail", en: "sail", cs: "plout", emoji: "⛵", category: "Slovesa" },
  { id: "type", en: "type", cs: "psát na klávesnici", emoji: "⌨️", category: "Slovesa" },

  // Přídavná jména
  { id: "big", en: "big", cs: "velký", emoji: "🐘", category: "Přídavná jména" },
  { id: "small", en: "small", cs: "malý", emoji: "🐜", category: "Přídavná jména" },
  { id: "tall", en: "tall", cs: "vysoký", emoji: "🦒", category: "Přídavná jména" },
  { id: "new", en: "new", cs: "nový", emoji: "🆕", category: "Přídavná jména" },
  { id: "old", en: "old", cs: "starý", emoji: "👴", category: "Přídavná jména" },
  { id: "young", en: "young", cs: "mladý", emoji: "👶", category: "Přídavná jména" },
  { id: "full", en: "full", cs: "plný", emoji: "🈵", category: "Přídavná jména" },
  { id: "empty", en: "empty", cs: "prázdný", emoji: "📭", category: "Přídavná jména" },
  { id: "loud", en: "loud", cs: "hlasitý", emoji: "🔊", category: "Přídavná jména" },
  { id: "quiet", en: "quiet", cs: "tichý", emoji: "🤫", category: "Přídavná jména" },
  { id: "wet", en: "wet", cs: "mokrý", emoji: "💦", category: "Přídavná jména" },
  { id: "dry", en: "dry", cs: "suchý", emoji: "🏜️", category: "Přídavná jména" },
  { id: "sharp", en: "sharp", cs: "ostrý", emoji: "🔪", category: "Přídavná jména" },
  { id: "soft", en: "soft", cs: "měkký", emoji: "🧸", category: "Přídavná jména" },
  { id: "hard", en: "hard", cs: "tvrdý", emoji: "🪨", category: "Přídavná jména" },
  { id: "round", en: "round", cs: "kulatý", emoji: "⚪", category: "Přídavná jména" },
  { id: "square", en: "square", cs: "čtvercový", emoji: "⬜", category: "Přídavná jména" },
  { id: "colorful", en: "colorful", cs: "barevný", emoji: "🌈", category: "Přídavná jména" },
  { id: "dark", en: "dark", cs: "tmavý", emoji: "🌑", category: "Přídavná jména" },
  { id: "bright", en: "bright", cs: "jasný", emoji: "🔆", category: "Přídavná jména" },
  { id: "sweet", en: "sweet", cs: "sladký", emoji: "🍬", category: "Přídavná jména" },
  { id: "sour", en: "sour", cs: "kyselý", emoji: "🍋", category: "Přídavná jména" },
  { id: "spicy", en: "spicy", cs: "pálivý", emoji: "🌶️", category: "Přídavná jména" },
  { id: "salty", en: "salty", cs: "slaný", emoji: "🧂", category: "Přídavná jména" },
  { id: "curly", en: "curly", cs: "kudrnatý", emoji: "🦱", category: "Přídavná jména" },
  { id: "bald", en: "bald", cs: "plešatý", emoji: "🦲", category: "Přídavná jména" },
  { id: "cute", en: "cute", cs: "roztomilý", emoji: "🥰", category: "Přídavná jména" },
  { id: "sick", en: "sick", cs: "nemocný", emoji: "🤒", category: "Přídavná jména" },
  { id: "tired", en: "tired", cs: "unavený", emoji: "😴", category: "Přídavná jména" },
  { id: "hungry", en: "hungry", cs: "hladový", emoji: "🤤", category: "Přídavná jména" },
  { id: "thirsty", en: "thirsty", cs: "žíznivý", emoji: "🚰", category: "Přídavná jména" },
  { id: "scared", en: "scared", cs: "vystrašený", emoji: "😱", category: "Přídavná jména" },
  { id: "surprised", en: "surprised", cs: "překvapený", emoji: "😮", category: "Přídavná jména" },
  { id: "angry", en: "angry", cs: "naštvaný", emoji: "😠", category: "Přídavná jména" },
  { id: "happy", en: "happy", cs: "šťastný", emoji: "😀", category: "Přídavná jména" },
  { id: "sad", en: "sad", cs: "smutný", emoji: "😢", category: "Přídavná jména" },
  { id: "fast", en: "fast", cs: "rychlý", emoji: "⚡", category: "Přídavná jména" },
  { id: "slow", en: "slow", cs: "pomalý", emoji: "🐌", category: "Přídavná jména" },
  { id: "strong", en: "strong", cs: "silný", emoji: "💪", category: "Přídavná jména" },
  { id: "heavy", en: "heavy", cs: "těžký", emoji: "🏋️", category: "Přídavná jména" },
  { id: "light", en: "light", cs: "lehký", emoji: "🪶", category: "Přídavná jména" },
  { id: "clean", en: "clean", cs: "čistý", emoji: "✨", category: "Přídavná jména" },
  { id: "dirty", en: "dirty", cs: "špinavý", emoji: "🦨", category: "Přídavná jména" },

  // Barvy
  { id: "red", en: "red", cs: "červená", emoji: "🔴", category: "Barvy" },
  { id: "blue", en: "blue", cs: "modrá", emoji: "🔵", category: "Barvy" },
  { id: "green", en: "green", cs: "zelená", emoji: "🟢", category: "Barvy" },
  { id: "yellow", en: "yellow", cs: "žlutá", emoji: "🟡", category: "Barvy" },
  { id: "purple", en: "purple", cs: "fialová", emoji: "🟣", category: "Barvy" },
  { id: "pink", en: "pink", cs: "růžová", emoji: "🩷", category: "Barvy" },
  { id: "black", en: "black", cs: "černá", emoji: "⚫", category: "Barvy" },
  { id: "white", en: "white", cs: "bílá", emoji: "⚪", category: "Barvy" },
  { id: "brown", en: "brown", cs: "hnědá", emoji: "🟤", category: "Barvy" },
  { id: "gray", en: "gray", cs: "šedá", emoji: "🩶", category: "Barvy" },

  // Čísla
  { id: "one", en: "one", cs: "jedna", emoji: "1️⃣", category: "Čísla" },
  { id: "two", en: "two", cs: "dva", emoji: "2️⃣", category: "Čísla" },
  { id: "three", en: "three", cs: "tři", emoji: "3️⃣", category: "Čísla" },
  { id: "four", en: "four", cs: "čtyři", emoji: "4️⃣", category: "Čísla" },
  { id: "five", en: "five", cs: "pět", emoji: "5️⃣", category: "Čísla" },
  { id: "six", en: "six", cs: "šest", emoji: "6️⃣", category: "Čísla" },
  { id: "seven", en: "seven", cs: "sedm", emoji: "7️⃣", category: "Čísla" },
  { id: "eight", en: "eight", cs: "osm", emoji: "8️⃣", category: "Čísla" },
  { id: "nine", en: "nine", cs: "devět", emoji: "9️⃣", category: "Čísla" },
  { id: "ten", en: "ten", cs: "deset", emoji: "🔟", category: "Čísla" },
  { id: "eleven", en: "eleven", cs: "jedenáct", emoji: "1️⃣1️⃣", category: "Čísla" },
  { id: "twelve", en: "twelve", cs: "dvanáct", emoji: "1️⃣2️⃣", category: "Čísla" },
  { id: "thirteen", en: "thirteen", cs: "třináct", emoji: "1️⃣3️⃣", category: "Čísla" },
  { id: "fourteen", en: "fourteen", cs: "čtrnáct", emoji: "1️⃣4️⃣", category: "Čísla" },
  { id: "fifteen", en: "fifteen", cs: "patnáct", emoji: "1️⃣5️⃣", category: "Čísla" },
  { id: "sixteen", en: "sixteen", cs: "šestnáct", emoji: "1️⃣6️⃣", category: "Čísla" },
  { id: "seventeen", en: "seventeen", cs: "sedmnáct", emoji: "1️⃣7️⃣", category: "Čísla" },
  { id: "eighteen", en: "eighteen", cs: "osmnáct", emoji: "1️⃣8️⃣", category: "Čísla" },
  { id: "nineteen", en: "nineteen", cs: "devatenáct", emoji: "1️⃣9️⃣", category: "Čísla" },
  { id: "twenty", en: "twenty", cs: "dvacet", emoji: "2️⃣0️⃣", category: "Čísla" },

  // Čas a kalendář
  { id: "morning", en: "morning", cs: "ráno", emoji: "🌅", category: "Čas a kalendář" },
  { id: "afternoon", en: "afternoon", cs: "odpoledne", emoji: "🌇", category: "Čas a kalendář" },
  { id: "evening", en: "evening", cs: "večer", emoji: "🌆", category: "Čas a kalendář" },
  { id: "night", en: "night", cs: "noc", emoji: "🌃", category: "Čas a kalendář" },
  { id: "calendar", en: "calendar", cs: "kalendář", emoji: "📅", category: "Čas a kalendář" },
  { id: "hour", en: "hour", cs: "hodina", emoji: "🕜", category: "Čas a kalendář" },
  { id: "minute", en: "minute", cs: "minuta", emoji: "⏱️", category: "Čas a kalendář" },
  { id: "spring", en: "spring", cs: "jaro", emoji: "🌸", category: "Čas a kalendář" },
  { id: "summer", en: "summer", cs: "léto", emoji: "☀️", category: "Čas a kalendář" },
  { id: "autumn", en: "autumn", cs: "podzim", emoji: "🍂", category: "Čas a kalendář" },
  { id: "winter", en: "winter", cs: "zima", emoji: "❄️", category: "Čas a kalendář" },
  { id: "birthday", en: "birthday", cs: "narozeniny", emoji: "🎉", category: "Čas a kalendář" },
  { id: "alarm_clock", en: "alarm clock", cs: "budík", emoji: "⏰", category: "Čas a kalendář" },
  { id: "hourglass", en: "hourglass", cs: "přesýpací hodiny", emoji: "⏳", category: "Čas a kalendář" },
  { id: "week", en: "week", cs: "týden", emoji: "📆", category: "Čas a kalendář" },
  { id: "vacation", en: "vacation", cs: "prázdniny", emoji: "🏖️", category: "Čas a kalendář" },

  // Rodina
  { id: "mother", en: "mother", cs: "matka", emoji: "👩", category: "Rodina" },
  { id: "father", en: "father", cs: "otec", emoji: "👨", category: "Rodina" },
  { id: "sister", en: "sister", cs: "sestra", emoji: "👧", category: "Rodina" },
  { id: "brother", en: "brother", cs: "bratr", emoji: "👦", category: "Rodina" },
  { id: "grandmother", en: "grandmother", cs: "babička", emoji: "👵", category: "Rodina" },
  { id: "grandfather", en: "grandfather", cs: "dědeček", emoji: "👴", category: "Rodina" },
  { id: "baby", en: "baby", cs: "miminko", emoji: "👶", category: "Rodina" },
  { id: "cousin", en: "cousin", cs: "bratranec", emoji: "🧑", category: "Rodina" },
  { id: "family", en: "family", cs: "rodina", emoji: "👨‍👩‍👧‍👦", category: "Rodina" },
  { id: "twins", en: "twins", cs: "dvojčata", emoji: "👯", category: "Rodina" },

  // Různé
  { id: "music_note", en: "music note", cs: "nota", emoji: "🎵", category: "Různé" },
  { id: "robot", en: "robot", cs: "robot", emoji: "🤖", category: "Různé" },
  { id: "alien", en: "alien", cs: "mimozemšťan", emoji: "👽", category: "Různé" },
  { id: "ghost", en: "ghost", cs: "duch", emoji: "👻", category: "Různé" },
  { id: "monster", en: "monster", cs: "příšera", emoji: "👹", category: "Různé" },
  { id: "dragon", en: "dragon", cs: "drak", emoji: "🐉", category: "Různé" },
  { id: "castle", en: "castle", cs: "hrad", emoji: "🏰", category: "Různé" },
  { id: "gem", en: "gem", cs: "drahokam", emoji: "💎", category: "Různé" },
  { id: "lightbulb", en: "lightbulb", cs: "žárovka", emoji: "💡", category: "Různé" },
  { id: "gear", en: "gear", cs: "ozubené kolo", emoji: "⚙️", category: "Různé" },
  { id: "magnet", en: "magnet", cs: "magnet", emoji: "🧲", category: "Různé" },
  { id: "target", en: "target", cs: "terč", emoji: "🎯", category: "Různé" },
  { id: "game_controller", en: "game controller", cs: "herní ovladač", emoji: "🎮", category: "Různé" },
  { id: "dice", en: "dice", cs: "hrací kostka", emoji: "🎲", category: "Různé" },
  { id: "mermaid", en: "mermaid", cs: "mořská panna", emoji: "🧜", category: "Různé" },
  { id: "fairy", en: "fairy", cs: "víla", emoji: "🧚", category: "Různé" },
  { id: "pirate", en: "pirate", cs: "pirát", emoji: "🏴‍☠️", category: "Různé" },
  { id: "magic_wand", en: "magic wand", cs: "kouzelná hůlka", emoji: "🪄", category: "Různé" },
  { id: "crystal_ball", en: "crystal ball", cs: "křišťálová koule", emoji: "🔮", category: "Různé" },
  { id: "compass", en: "compass", cs: "kompas", emoji: "🧭", category: "Různé" },
  { id: "tent", en: "tent", cs: "stan", emoji: "⛺", category: "Různé" },
  { id: "firework", en: "firework", cs: "ohňostroj", emoji: "🎆", category: "Různé" },
  { id: "anchor", en: "anchor", cs: "kotva", emoji: "⚓", category: "Různé" },
  { id: "mailbox", en: "mailbox", cs: "poštovní schránka", emoji: "📪", category: "Různé" },
  { id: "lock", en: "lock", cs: "zámek", emoji: "🔒", category: "Různé" },
  { id: "ufo", en: "ufo", cs: "UFO", emoji: "🛸", category: "Různé" },
  { id: "shooting_star", en: "shooting star", cs: "padající hvězda", emoji: "🌠", category: "Různé" },
  { id: "satellite", en: "satellite", cs: "satelit", emoji: "🛰️", category: "Různé" },
  { id: "shield", en: "shield", cs: "štít", emoji: "🛡️", category: "Různé" },
  { id: "sword", en: "sword", cs: "meč", emoji: "⚔️", category: "Různé" },
];

function startsWithVowelSound(word: string): boolean {
  return /^[aeiou]/i.test(word);
}

function withArticle(word: string): string {
  return `${startsWithVowelSound(word) ? "an" : "a"} ${word}`;
}

// Clothing words that are always plural in English (you wear "pants", never
// "a pants") — withArticle's a/an heuristic only looks at the first sound,
// not grammatical number, so these need to skip the article entirely
// instead of getting a false "a pants".
const PLURAL_ONLY_CLOTHING = new Set([
  "pants",
  "shorts",
  "socks",
  "shoes",
  "sneakers",
  "boots",
  "gloves",
  "sunglasses",
]);

function clothingPhrase(w: string, adjective?: string): string {
  const core = adjective ? `${adjective} ${w}` : w;
  return PLURAL_ONLY_CLOTHING.has(w) ? core : withArticle(core);
}

function hashString(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return Math.abs(h);
}

// Several everyday sentences per category instead of one repeated pattern —
// which template a word gets is picked deterministically from the word
// itself (see buildExampleSentence), so the same word always shows the same
// sentence but different words in the same category read differently.
const SENTENCE_TEMPLATES: Record<string, ((w: string) => string)[]> = {
  Zvířata: [
    (w) => `I have ${withArticle(w)} at home.`,
    (w) => `Look, ${withArticle(w)}!`,
    (w) => `I saw ${withArticle(w)} at the zoo.`,
  ],
  Jídlo: [
    (w) => `I eat ${w} every day.`,
    (w) => `Can I have some ${w}, please?`,
    (w) => `We bought some ${w} at the store.`,
  ],
  Oblečení: [
    (w) => `I am wearing ${clothingPhrase(w)} today.`,
    (w) => `I need ${clothingPhrase(w, "new")}.`,
    (w) => `She bought ${clothingPhrase(w, "new")} yesterday.`,
  ],
  Doprava: [
    (w) => `We went to school by ${w}.`,
    (w) => `I love riding in ${withArticle(w)}.`,
    (w) => `Look at that ${w} on the road!`,
  ],
  Doma: [
    (w) => `There is ${withArticle(w)} in my room.`,
    (w) => `We bought a new ${w} for our house.`,
    (w) => `Please clean the ${w}.`,
  ],
  Povolání: [
    (w) => `My uncle is ${withArticle(w)}.`,
    (w) => `When I grow up, I want to be ${withArticle(w)}.`,
    (w) => `The ${w} helps people every day.`,
  ],
  "Přídavná jména": [
    (w) => `My dog is ${w}.`,
    (w) => `This box is very ${w}.`,
    (w) => `I feel ${w} today.`,
  ],
  "Příroda a počasí": [
    (w) => `I can see the ${w}.`,
    (w) => `We like to watch the ${w}.`,
    (w) => `The ${w} is beautiful today.`,
  ],
  Rodina: [
    (w) => `This is my ${w}.`,
    (w) => `My ${w} lives with us.`,
    (w) => `I love my ${w} very much.`,
  ],
  Slovesa: [
    (w) => `I like to ${w} every day.`,
    (w) => `Let's ${w} together!`,
    (w) => `She can ${w} very well.`,
  ],
  "Sport a koníčky": [
    (w) => `I play ${w} with my friends.`,
    (w) => `My favorite sport is ${w}.`,
    (w) => `We watched ${w} on TV.`,
  ],
  Tělo: [
    (w) => `My ${w} hurts a little.`,
    (w) => `Please wash your ${w}.`,
    (w) => `Touch your ${w}.`,
  ],
  "Čas a kalendář": [
    (w) => `I wake up in the ${w}.`,
    (w) => `See you next ${w}!`,
    (w) => `We have a party this ${w}.`,
  ],
  Čísla: [
    (w) => `I have ${w} apples.`,
    (w) => `Count to ${w} with me.`,
    (w) => `There are ${w} birds in the tree.`,
  ],
  Škola: [
    (w) => `I need ${withArticle(w)} for school.`,
    (w) => `My teacher gave me ${withArticle(w)}.`,
    (w) => `Where is my ${w}?`,
  ],
  Barvy: [
    (w) => `My favorite color is ${w}.`,
    (w) => `The sky is ${w} today.`,
    (w) => `I have a ${w} bike.`,
  ],
  Různé: [
    (w) => `Look, ${withArticle(w)}!`,
    (w) => `I drew a picture of ${withArticle(w)}.`,
    (w) => `The story has ${withArticle(w)} in it.`,
  ],
};

const DEFAULT_SENTENCE_TEMPLATES: ((w: string) => string)[] = [
  (w) => `I like ${w}.`,
  (w) => `I see ${withArticle(w)}.`,
];

/**
 * A short, English-only example sentence for a flashcard word — several
 * everyday sentence patterns per grammatical category (animals, food,
 * verbs, adjectives, ...) instead of one generic pattern repeated for
 * every word. Which pattern a word gets is stable (hashed from the word
 * itself), so the same word always shows the same sentence.
 */
export function buildExampleSentence(word: Pick<EnglishWord, "en" | "category">): string {
  const w = word.en;
  const templates = SENTENCE_TEMPLATES[word.category] ?? DEFAULT_SENTENCE_TEMPLATES;
  const template = templates[hashString(w) % templates.length];
  return template(w);
}
